# config/classes.yaml
classes:
  # ======================
  # Контроллеры (controllers/)
  # ======================
  controller\AdminController:
    class: controller\AdminController
    dependencies:
      - services\AdminService
    file: /controllers/AdminController.php

  controller\MainController:
    class: controller\MainController
    dependencies:
      - services\MainService
    file: /controllers/MainController.php

  controller\RegistrationController:
    class: controller\RegistrationController
    dependencies:
      - services\RegistrationService
    file: /controllers/RegistrationController.php

  controller\LoginController:
    class: controller\LoginController
    dependencies:
      - services\LoginService
    file: /controllers/LoginController.php

  controller\AuthorizationController:
    class: controller\AuthorizationController
    dependencies:
      - services\AuthorizationService
    file: /controllers/AuthorizationController.php

  controller\ClickStatisticController:
    class: controller\ClickStatisticController
    dependencies:
      - services\ClickStatisticService
    file: /controllers/ClickStatisticController.php

  # ======================
  # Сервисы (services/)
  # ======================
  services\AdminService:
    class: services\AdminService
    dependencies:
      - MyTemplate\TemplateFacade
      - repositories\ClickStatisticRepository
    file: /services/AdminService.php

  services\MainService:
    class: services\MainService
    dependencies:
      - MyTemplate\TemplateFacade
      - repositories\FoodRepository
      - repositories\UserRepository
      - repositories\OrderRepository
      - services\AuthorizationService
    file: /services/MainService.php

  services\RegistrationService:
    class: services\RegistrationService
    dependencies:
      - repositories\UserRepository
      - MyTemplate\TemplateFacade
      - services\MailService
    file: /services/RegistrationService.php

  services\LoginService:
    class: services\LoginService
    dependencies:
      - repositories\UserRepository
      - MyTemplate\TemplateFacade
      - services\MailService
    file: /services/LoginService.php

  services\AuthorizationService:
    class: services\AuthorizationService
    dependencies:
      - repositories\UserRepository
      - services\LoginService
    file: /services/AuthorizationService.php

  services\MailService:
    class: services\MailService
    dependencies:
      - MyTemplate\TemplateFacade
    file: /services/MailService.php

  services\ClickStatisticService:
    class: services\ClickStatisticService
    dependencies:
      - repositories\ClickStatisticRepository
    file: /services/ClickStatisticService.php

  services\TranslatorService:
    class: services\TranslatorService
    dependencies: []
    file: /services/TranslatorService.php


  # ======================
  # Репозитории (repositories/)
  # ======================
  repositories\FoodRepository:
    class: repositories\FoodRepository
    dependencies: []
    file: /repositories/FoodRepository.php

  repositories\UserRepository:
    class: repositories\UserRepository
    dependencies: []
    file: /repositories/UserRepository.php

  repositories\OrderRepository:
    class: repositories\OrderRepository
    dependencies: []
    file: /repositories/OrderRepository.php

  repositories\ClickStatisticRepository:
    class: repositories\ClickStatisticRepository
    dependencies: []
    file: /repositories/ClickStatisticRepository.php

  repositories\AbstractRepository:
    class: repositories\AbstractRepository
    dependencies: [ ]
    file: /repositories/AbstractRepository.php

  # ======================
  # Шаблонизатор (MyTemplate/)
  # ======================
  MyTemplate\TemplateFacade:
    class: MyTemplate\TemplateFacade
    dependencies: []
    file: /templateEngine/TemplateFacade.php

  # ======================
  # Утилиты (utils/)
  # ======================

  utils\Router:
    class: utils\Router
    dependencies:
      - utils\ClassLoader
    file: /utils/Router.php

  utils\ClassLoader:
    class: utils\ClassLoader
    dependencies: []
    file: /utils/ClassLoader.php

  # ======================
  # Модели (models/)
  # ======================
  models\ClickStatistic:
    class: models\ClickStatistic
    dependencies: []
    file: /models/ClickStatistic.php
  models\Food:
    class: models\Food
    dependencies: []
    file: /models/Food.php
  models\User:
    class: models\User
    dependencies: []
    file: /models/User.php
  models\Order:
    class: models\Order
    dependencies: []
    file: /models/Order.php